---
collections:
  - name: community.postgresql
    version: ">=3.0.0"
  - name: ansible.posix     # provides the 'mount' module we need for disk handling
    version: ">=1.5.0"
  - name: community.general # provides the 'filesystem' module (mkfs wrapper)
    version: ">=8.0.0"
